INSERT INTO TESTELSA."PUBLIC".GROUPS (GROUPNAME, TASKSCORES) values ('Kettupoppoo', 250);
INSERT INTO TESTELSA."PUBLIC".GROUPS (GROUPNAME, TASKSCORES) values ('Jermut', 20500);
INSERT INTO TESTELSA."PUBLIC".USERS (USERNAME, ROLE, POINTS, GROUPID, COMPLETEDTASKS, CONTACTPERSONUSERID) values ('Jermu', 'Testaaja', 2000, 1, ('Himmeli', 'Helpperi'), 1);
INSERT INTO TESTELSA."PUBLIC".USERS (USERNAME, ROLE, POINTS, GROUPID, COMPLETEDTASKS, CONTACTPERSONUSERID) values ('Jouni', 'Reagoija', 2000, 2, ('Himmeli'), 1);
INSERT INTO TESTELSA."PUBLIC".USERS (USERNAME, ROLE, POINTS, GROUPID, COMPLETEDTASKS, CONTACTPERSONUSERID) values ('Elmo', 'Kehittäjä', 2000, 2, ('Shakki', 'ElsaMaster'), 1);
INSERT INTO TESTELSA."PUBLIC".USERS (USERNAME, ROLE, POINTS, GROUPID, COMPLETEDTASKS, CONTACTPERSONUSERID) values ('Rekku', 'Testaaja', 2000, 2, ('Orvokki', 'Ruiskaunokki'), 1);
INSERT INTO TESTELSA."PUBLIC".USERS (USERNAME, ROLE, POINTS, GROUPID, COMPLETEDTASKS, CONTACTPERSONUSERID) values ('Miika', 'Autentikoija', 2000, 2, ('Orvokki', 'Ruiskaunokki'), 1);
INSERT INTO TESTELSA."PUBLIC".USERS (USERNAME, ROLE, POINTS, GROUPID, COMPLETEDTASKS, CONTACTPERSONUSERID) values ('u', 'Uneksija', 2000, 1, ('ElsaMaster'), 1);